import PptxGenJS from "pptxgenjs";

export const runtime = "nodejs";

type SlideInput = {
  title?: string;
  bullets?: string[];
  imageQuery?: string;
  videoQuery?: string;
  interactivePrompt?: string;
};

type ExportPayload = {
  meta?: { subject?: string; topic?: string; grade?: string };
  slides: SlideInput[];
};

function clean(s: unknown, max = 180) {
  const t = String(s ?? "").replace(/\s+/g, " ").trim();
  return t.length > max ? t.slice(0, max - 1) + "…" : t;
}

export async function POST(req: Request) {
  try {
    const body = (await req.json()) as ExportPayload;

    if (!body?.slides?.length) {
      return new Response("No slides provided", { status: 400 });
    }

    const pptx = new PptxGenJS();
    pptx.layout = "LAYOUT_WIDE";

    const subject = clean(body.meta?.subject, 60);
    const topic = clean(body.meta?.topic, 90);
    const grade = clean(body.meta?.grade, 20);

    const title = clean([subject, topic].filter(Boolean).join(": ") || "Lesson Slides", 120);

    // Title slide
    {
      const s = pptx.addSlide();
      s.addText(title, { x: 0.7, y: 1.4, w: 12.0, h: 1.0, fontSize: 34, bold: true });
      if (grade) s.addText(`Grade/Class: ${grade}`, { x: 0.7, y: 2.5, w: 12.0, h: 0.5, fontSize: 18 });
      s.addText("Generated by LessonForge", { x: 0.7, y: 7.1, w: 12.0, h: 0.3, fontSize: 10, italic: true });
    }

    // Content slides
    for (const it of body.slides) {
      const s = pptx.addSlide();

      s.addText(clean(it.title || "Slide", 90), {
        x: 0.7, y: 0.6, w: 12.0, h: 0.6, fontSize: 28, bold: true,
      });

      const bullets = (it.bullets ?? []).map((b) => clean(b, 160)).filter(Boolean).slice(0, 9);
      const bulletText = bullets.length ? bullets.map((b) => `• ${b}`).join("\n") : "• (No bullet points provided)";

      s.addText(bulletText, {
        x: 0.9, y: 1.4, w: 12.0, h: 4.6, fontSize: 18, lineSpacingMultiple: 1.15,
      });

      const activity = clean(it.interactivePrompt, 220);
      if (activity) {
        s.addText(`Classroom Activity: ${activity}`, {
          x: 0.9, y: 6.4, w: 12.0, h: 0.6, fontSize: 14, italic: true,
        });
      }

      const footer = [
        it.imageQuery ? `Image: ${clean(it.imageQuery, 90)}` : "",
        it.videoQuery ? `Video: ${clean(it.videoQuery, 90)}` : "",
      ].filter(Boolean).join(" | ");

      if (footer) {
        s.addText(footer, { x: 0.9, y: 7.2, w: 12.0, h: 0.3, fontSize: 10 });
      }
    }

    // IMPORTANT: ArrayBuffer output + safe conversion
    const ab = (await (pptx as any).write("arraybuffer")) as ArrayBuffer;
    const buf = Buffer.from(new Uint8Array(ab));

    const filename = `LessonForge-${Date.now()}.pptx`;

    return new Response(buf, {
      status: 200,
      headers: {
        "Content-Type": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "Content-Disposition": `attachment; filename="${filename}"`,
        "Cache-Control": "no-store",
      },
    });
  } catch (err: any) {
    console.error("EXPORT_PPTX_ERROR:", err);
    return new Response(`PPTX export failed: ${String(err?.message ?? err)}`, { status: 500 });
  }
}
